### PR TITLE
Keep all information from denite when adding icon

### PR DESCRIPTION
**Pull request by carlitux**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
* Solve this issue https://github.com/ryanoasis/vim-devicons/issues/216
* Update sources to process like file_mru directory_mru

#### How should this be manually tested?
Enable denite and list buffers, file_mru, directory_mru, those are new features

#### What are the relevant tickets (if any)?
https://github.com/ryanoasis/vim-devicons/issues/216

### CODE REVIEW

**Comment by ryanoasis** [comment]
@carlitux Awesome, thanks for this! 👍

**Comment by maxnordlund** [comment]
I noticed all tabs has been converted to spaces, which makes at least me a bit confused as to what has actually changed. 

But maybe it's not really important in the end.

**Comment by ryanoasis** [comment]
@maxnordlund Yeah that's a good point/catch.

@carlitux Could you amend your commit and revert the purely indentation changes? That way it is a little easier to diff the changes.

**Comment by carlitux** [comment]
@ryanoasis done.

Just a comment, would be good to add a .editorconfig to use that setup.

**Comment by ryanoasis** [comment]
Thanks. Good idea, we should add that.

I think there is not consistency between the files but there should be!

**Comment by ryanoasis** [comment]
Looks good to me :heart:

**Pull request merged**
