### PR TITLE
support for Powerline (not airline)

### PR DESCRIPTION
**Pull request by delphinus35**
I wrote codes for supporting [Powerline][] (not airline!).

[Powerline]: https://github.com/powerline/powerline

Because Powerline is written in Python, this codes is also written in Python. You can install this with `pip` command to use these segments.

example:

```sh
$ pip install -U --user git+https://github.com/delphinus35/vim-devicons@for-powerline
```

And write in Powerline config file.

```json
{
	"segments": {
		"left": [

...

			{
				"function": "powerlinex.segment.webdevicons.webdevicons",
				"priority": 10,
				"draw_soft_divider": false,
				"after": "  "
			},

...

		],
		"right": [

...

			{
				"function": "powerlinex.segment.webdevicons.webdevicons_file_format",
				"draw_soft_divider": false,
				"exclude_modes": ["nc"],
				"priority": 90
			},

...

		]
	}
}
```

##### `file_format` duplication

ref #73

In writing, I noticed the Powerline `file_encoding` segment is duplicated with return values from `WebDevIconsGetFileFormatSymbol()`.

* Should `WebDevIconsGetFileFormatSymbol()` return the penguin symbol only and no `file_encoding` string?

or

* Should I implement this logic in Python code?

### CODE REVIEW

**Comment by ryanoasis** [comment]
First off awesome work thanks. It will be great to support Powerline (I used to use it in Vim and looks like a lot of people still do).

> Should WebDevIconsGetFileFormatSymbol() return the penguin symbol only and no file_encoding string?

You are 100% correct that this should be changed to return file format **only**. That would meet the expectations of the function name *and* cleaner API-like usage. I'm violating the single responsibility principle :blush: 

The caller which uses this function currently then should and can be updated to add `&fenc` separately, so instead of:
```vim
let w:airline_section_y = ' %{WebDevIconsGetFileFormatSymbol()} '
```

It should be something like (syntax might be a bit off):
```vim
let w:airline_section_y = ' %{&fenc . WebDevIconsGetFileFormatSymbol()} '
```

This would be a better separation of concerns and allow you to use the original function properly as you described.

So yes I am all for your suggested change and I can make the change above too if you do not.

I haven't had a chance to pull your code and setup Powerline but I will when I get a chance :smile:

**Comment by ryanoasis** [comment]
Targeted for v0.6.0 release :smile:

**Comment by ryanoasis** [comment]
I finally got powerline installed and setup working in vim but its been a while since I've used it. I might need some helping getting the config to work. Thanks again.

**Comment by delphinus35** [comment]
I've forgotten that Powerline has two install processes, with pip or with vim directly. You might use the latter, and now I think that is preferable. I rewrite the process below. (and added slight change to for-powerline branch.)

----

#### 1. add setting for .vimrc

I like NeoBundle :)

```vim
NeoBundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
"NeoBundle 'ryanoasis/vim-devicons'
NeoBundle 'delphinus35/vim-devicons', {'rev': 'for-powerline'}
```

[sample minimal .vimrc](https://gist.github.com/fd77b378bb73d26edb79)

#### 2. powerline setting

```sh
$ mkdir ~/.config

# copy setting
$ cp -r ~/.vim/bundle/powerline/powerline/config_files ~/.config/powerline

$ vim ~/.config/powerline/themes/vim/default.json
```

add diff below.

```diff
diff -ru powerline.orig/themes/vim/default.json powerline/themes/vim/default.json
--- powerline.orig/themes/vim/default.json	2015-08-17 23:48:11.000000000 +0900
+++ powerline/themes/vim/default.json	2015-08-17 23:41:37.000000000 +0900
@@ -6,6 +6,12 @@
 				"exclude_modes": ["nc"]
 			},
 			{
+				"function": "vim_devicons.powerline.segments.webdevicons",
+				"priority": 10,
+				"draw_soft_divider": false,
+				"after": "  "
+			},
+			{
 				"function": "visual_range",
 				"include_modes": ["v", "V", "^V", "s", "S", "^S"],
 				"priority": 10
@@ -79,9 +85,15 @@
 		],
 		"right": [
 			{
-				"function": "file_format",
+				"function": "vim_devicons.powerline.segments.webdevicons_file_format",
 				"draw_soft_divider": false,
 				"exclude_modes": ["nc"],
+				"priority": 90
+			},
+			{
+				"function": "file_format",
+				"draw_soft_divider": true,
+				"exclude_modes": ["nc"],
 				"priority": 60
 			},
 			{
```

[sample default.json](https://gist.github.com/645d31cd8bf82978082a)

----

That's it. Please try this.

**Comment by ryanoasis** [comment]
Got it working. Thanks! :+1: 

Now to do some more testing and documentation and this should be ready for v0.6.0 :tada:

**Comment by ryanoasis** [comment]
@delphinus35 I have this merged into [0.6.0](https://github.com/ryanoasis/vim-devicons/tree/0.6.0), if you could take a look and provide any feedback, particularly the doc section I added: https://github.com/ryanoasis/vim-devicons/tree/0.6.0#powerline-setup

Thanks

**Comment by delphinus35** [comment]
* sorry. I have found an unnecessary file: `setup.py`. I removed this in commit 5c311d0.
* I read setup instructions in README. It seems almost perfect. But one point, README has `g:webdevicons_enable_powerline`, and I cannot find it in codes. Is this needed?

**Comment by ryanoasis** [comment]
* Oh? Okay I will re-pull and re-test without that file :smile:
* You are correct `g:webdevicons_enable_powerline` is not needed. I will update the readme. I think I added that before I pulled in and tested your changes. Things just "work" once it is setup so no disable/enabling from the plugin. Good catch thanks :+1:

**Pull request merged**
