### PR TITLE
Added support for Elixir

### PR DESCRIPTION
**Pull request by akoutmos**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
Adds support for Elixir file types

#### How should this be manually tested?
Open up a .ex, .exs, and .eex file and you should see the Elixir icon

#### Screenshots (if appropriate or helpful)
image

### CODE REVIEW

**Comment by alexparker** [comment]
Bump this! Just forked the repo, and merged this into my fork 👍  Need me my elixir icons :)

**Comment by HendrikPetertje** [comment]
bumpity bump. Would love the nice drops of elixir in my vim

**Comment by kubaugustyn** [comment]
Bump :)

**Comment by antmachine** [comment]
bump :taco:

**Comment by ryanoasis** [comment]
Sorry for the delay. Thanks @akoutmos

**Pull request merged**
