### PR TITLE
Add doc/tags.

### PR DESCRIPTION
**Pull request by Doron-Behar**

### CODE REVIEW

**Comment by ryanoasis** [comment]
Thanks but I think the typical way to handle this is to actually ignore the doc/tags from the repo not add them: https://github.com/search?utf8=%E2%9C%93&q=language%3Avim+doc+tags&type=Issues&ref=searchresults

I would recommend submitting a PR for ignoring them instead.

Any additional thoughts: @blueyed @her @lerrua @delphinus @mhartington ?

**Comment by blueyed** [comment]
Yeah, it's better to ignore them.

In this regard: the docs define a lot of tags, e.g. all of the `readme-*` once that should be prefixed with `devicons-` instead.

**Comment by blueyed** [comment]
I recommend to close this PR without merging.

**Comment by ryanoasis** [comment]
> In this regard: the docs define a lot of tags, e.g. all of the readme-* once that should be prefixed with devicons- instead.

Ah good point. Looks like this can be easily fixed, the [current build process](https://github.com/ryanoasis/vim-devicons/wiki/Development-Workflow) uses [`html2vimdoc`](https://github.com/xolox/vim-tools/blob/master/html2vimdoc.py) and there is a flag to do this: `--title` :smile:

**Comment by ryanoasis** [comment]
@Doron-Behar Please open a PR for adding a proper `.gitignore` for the doc/tags issue. I will give you sometime to do so (maybe until next weekend) else I will take care of this myself. Thanks

**Comment by blueyed** [comment]
btw: I recommend adding `tags` to your global gitignore, since it's also used by `ctags` etc.

**Pull request closed without merging**
