### PR TITLE
Normalize variable declarations with a set function

### PR DESCRIPTION
**Pull request by kutsan**
`s:set()` function declares variables with its default value like in built-in `get()` function style.

### CODE REVIEW

**Comment by ryanoasis** [comment]
Very nice. I've wanted to do something with those variables :blush:

**Comment by kutsan** [comment]
I don't know about you but I think using global variables that bountifully is not a right thing. I think options should be kept inside one global vim dictionary, like `let g:devicons = {}`. Obviously it's too late to do that.

**Comment by ryanoasis** [comment]
You are right but never too late to do things correctly. We could do this for 1.0.0 as a breaking change. Ref: https://github.com/ryanoasis/vim-devicons/issues/77

**Comment by kutsan** [comment]
Oh, that's awesome. Then, I'm proposing `grepper`s method to handle this. We can even categorize configs inside that dictionary.

https://github.com/mhinz/vim-grepper/blob/635c14284aea79117f2cc9d07c18c8f6da23d85b/plugin/grepper.vim#L11-L110

**Comment by kutsan** [comment]
@mhinz Thank you so much for you comment on this. I'm going to still say this project should go for it.

**Pull request closed without merging**
