### PR TITLE
add icon for solidity with file extension .sol (using ether icon)

### PR DESCRIPTION
**Pull request by Adoliin**
#### Requirements (please check off with 'x')

- [X] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [X] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [X] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
This PR is to resolve  [#395](https://github.com/ryanoasis/vim-devicons/issues/395)

#### Any background context you can provide?
I noticed that there is no icons on Solidity files , so I searched for one in nerd fonts icons and chose the Ether icon since Solidity is the language for developing smart contracts on the Ethereum Virtual Machine 

#### Screenshots (if appropriate or helpful)
sol-vim

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
@Adoliin
Thanks.
Could you also add test?

**Comment by Adoliin** [comment]
@kazukazuinaina
Yes, sure!

**Comment by kazukazuinaina** [comment]
@Adoliin 
Thanks, Also, Could you sqhash merge commit?
I think [this commit](https://github.com/ryanoasis/vim-devicons/pull/396/commits/46ee3616baacd011cbd1e971e6522a5157a0ff91) is dirty.

**Comment by Adoliin** [comment]
> @Adoliin
> Thanks, Also, Could you sqhash merge commit?
> I think [this commit](https://github.com/ryanoasis/vim-devicons/pull/396/commits/46ee3616baacd011cbd1e971e6522a5157a0ff91) is dirty.

Sorry I did not get what you meant.
What commits should I squash?

**Comment by kazukazuinaina** [comment]
@Adoliin 

Don't worry, I've squash the commit and imported your commit into master.
Thanks for your contribution!

**Comment by Adoliin** [comment]
Nice :)
Your welcome!

**Pull request closed without merging**
