### PR TITLE
[update] python version in unit test

### PR DESCRIPTION
**Pull request by kazukazuinaina**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?

This Pull Request is to update python version in unit test.

Specifically, I upgraded the version from Python2 to Python3.

#### How should this be manually tested?

don't need.

##### New status unit test

> https://travis-ci.org/kazukazuinaina/vim-devicons/builds/642507585?utm_source=github_status&utm_medium=notification

#### What are the relevant tickets (if any)?

Nothings

#### Screenshots (if appropriate or helpful)

Nothings

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
@ryanoasis 
CI passing.

**Comment by ryanoasis** [comment]
Looks nice and clean now. I'm a bit behind here but I want to do a "release" since last one was last year

**Comment by kazukazuinaina** [comment]
@ryanoasis 
Looks good!
I think we should go forward!

**Comment by ryanoasis** [comment]
Yep. Let's do that then :)

**Comment by kazukazuinaina** [comment]
@ryanoasis 
Thanks for checking and merge!

**Pull request merged**
