### PR TITLE
feat(unite): add file_rec/async and file_rec/neovim

### LINKED ISSUE #131: Unite file_rec/async question
Is there any particular reason why you the icons won't work with unite's `file_rec/async` search method?

### PR DESCRIPTION
**Pull request by mhartington**
Closes #131

### CODE REVIEW

**Comment by ryanoasis** [comment]
Thanks for this :+1: . I will check and merge when I get some time

**Comment by ryanoasis** [comment]
feel free to test this out in [0.8.0 branch](https://github.com/ryanoasis/vim-devicons/tree/0.8.0)

Not fully tested but seems stable

**Comment by KabbAmine** [comment]
Looks really good :+1: 
Before pushing v0.8.0, it will be great  to add `file_rec/git` source, I've tested and it is working normally (No need of a new PR in my opinion).

**Comment by ryanoasis** [comment]
@KabbAmine Ah okay. Yep I will add that in. Good suggestion thanks!

**Comment by ryanoasis** [comment]
for reference: https://github.com/ryanoasis/vim-devicons/commit/d1c39a5988e8ce4af72ac5a61ed3078de0368a2e

**Pull request merged**
