### PR TITLE
[add] github_actions

### PR DESCRIPTION
**Pull request by kazukazuinaina**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
This patch is to update CI ( same test using vint ).
I suggest migrating from travis-ci to github-actions.
github-actions is much faster than travis-ci.
(The test is completed in just 7 seconds.)

#### How should this be manually tested?
Please see this status.

#### Any background context you can provide?
Nothings.

#### What are the relevant tickets (if any)?
Nothings.

#### Screenshots (if appropriate or helpful)
Nothings.

Could you check this Pull Request?

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
PS: github-actions may work if you merge!

**Comment by ryanoasis** [comment]
I want to spend some time looking through but it looks good! Great work here...

**Comment by kazukazuinaina** [comment]
ping: @ryanoasis

**Comment by ryanoasis** [comment]
Let's try it!

`.travis.yml` should get deleted once this is confirmed

**Comment by kazukazuinaina** [comment]
I will delete .travis.yml.
Is that Okay?

**Comment by ryanoasis** [comment]
Yes that's okay

**Pull request merged**
