### PR TITLE
Add android symbol

### PR DESCRIPTION
**Pull request by Freed-Wu**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
Add support for android.

#### Screenshots (if appropriate or helpful)

image
image
image

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
This is not a good idea.
Because every time a particular autocmd is executed, such as a status line update, `uname -a` is executed, which affects the overall performance of the Vim. Also, we have a cache to prevent this, but this patch messes up the cache we've created.

**Comment by kazukazuinaina** [comment]
I'm hesitant to merge this patch because I think it will affect the overall performance of Vim.

**Comment by Freed-Wu** [comment]
```{.vim}
  if executable('lsb_release')
  ......
  elseif system('uname -o') =~# 'Android'
  .....
  endif
```

i think for any linux distribution which keep linux standard base (lsb), it will not execuate `uname -o`. so it will not make them slower.

**Comment by kazukazuinaina** [comment]
I understand what you are saying.
But I don't know how many people use Vim and androidOS. And if uname command is not viable, I think you will have problems.

**Comment by Freed-Wu** [comment]
i readed the code of the part 'os_icon' of <https://github.com/romkatv/powerlevel10k>, in <https://github.com/romkatv/powerlevel10k/blob/master/internal/wizard.zsh#L442>, in fact, it also use `uname -o` to know the os is android. perhaps someone know are there any method to know the os type?

**Comment by Freed-Wu** [comment]
i notice in <https://github.com/ryanoasis/vim-devicons/blob/7d1c3aeb3b26c7fb7bcd7cb2bee67beb3e538db3/plugin/webdevicons.vim#L130> it allows user to define a variable `g:WebDevIconsOS`.
So
```{.vim}
  elseif get(g:, 'WebDevIconsOS') ==? 'Android' || executable('uname') && system('uname -o') =~# 'Android'
    let s:distro = ''
    return s:distro
  endif
```

`||` is a short circuit operation when `get(g:, 'WebDevIconsOS') ==? 'Android'` return 1 the expression must be 1 so it will not continue to call `system()`. it will not make vim slow.

**Comment by kazukazuinaina** [comment]
```vim
" scope: local
function s:isDarwin()
  if exists('s:is_darwin')
    return s:is_darwin
  endif

  if exists('g:WebDevIconsOS')
    let s:is_darwin = g:WebDevIconsOS ==? 'Darwin'
    return s:is_darwin
  endif

  if has('macunix')
    let s:is_darwin = 1
    return s:is_darwin
  endif

  if ! has('unix')
    let s:is_darwin = 0
    return s:is_darwin
  endif

  if system('uname -s') ==# "Darwin\n"
    let s:is_darwin = 1
  else
    let s:is_darwin = 0
  endif

  return s:is_darwin
endfunction
```

This function is used to determine whether a person is a Darwinian or not. While the code could certainly satisfy the requirements, we don't want to include it because of the potential for later maintenance costs or reduced readability of the code.
Also, I feel that very few people use Vim with Android 0S. So I want to close this patch for now. If a lot of people want this feature, then I will consider it then.
I'm sorry.

**Comment by Freed-Wu** [comment]
> Also, I feel that very few people use Vim with Android 0S.

See <https://github.com/termux/termux-app>. there are many linuxers who do their work in their androids by termux when they don't carry their linux computer. (if them have bluetooth keyboard, it will be better. if no, ssh to a windows pc of hotel also can work well.) i don't admit all of them use vim rather than other editors, but i believe the vimers among them is not only me.

Screenshot_2020-10-07-19-16-51-66_84d3000e3f4017145260f7618db1d683

in my humble opinion, after powerlevel10k.zsh (a zsh color theme) and airline.vim (airline-battery), if this plugin can support termux, i believe it will be better.

> While the code could certainly satisfy the requirements, we don't want to include it because of the potential for later maintenance costs or reduced readability of the code.

you are right. what about
```{.vim}
  elseif executable('uname') && system('uname -o') =~# 'Android'
    let s:distro = ''
    return s:distro
  endif
```
?

another way is
```{.vim}
  elseif $PREFIX =~# 'termux'
    let s:distro = ''
    return s:distro
  endif
```

**Pull request closed without merging**
