### PR TITLE
Add gentoo symbol

### PR DESCRIPTION
**Pull request by Freed-Wu**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
Add gentoo symbol
#### How should this be manually tested?
See Screenshots.
#### Screenshots (if appropriate or helpful)

image

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
@Freed-Wu 
I would appreciate it if you could provide a screenshot showing how it would be rendered in devicons.

**Comment by Freed-Wu** [comment]
image

**Comment by ryanoasis** [comment]
This is a good idea. I like it

**Comment by kazukazuinaina** [comment]
Thanks, I have merged this patch.

**Pull request merged**
