### PR TITLE
Add initial Travis CI with vim-vint linter

### PR DESCRIPTION
**Pull request by kutsan**
We can extend that later but I guess for now it's a good start.

Ref https://github.com/ryanoasis/vim-devicons/issues/122

### CODE REVIEW

**Comment by kutsan** [comment]
https://github.com/ryanoasis/vim-devicons/blob/390b0142f1b6f02bdecc4867009e83c9ecc01db2/plugin/webdevicons.vim#L438

@ryanoasis It should be `l:altwinnr`.

**Comment by ryanoasis** [comment]
@kutsan Very cool! Nice, already paying dividends.

I had vint setup setup locally at one point, apparently not anymore.

Hmm I would have to read up on `:h silent`. There might have been a reason for it but honestly not sure, possibly that command will fail and we want to ignore

```
":silent!" is useful to execute a command that may
			fail, but the failure is to be ignored.
```

Either way really like having linting! Big fan of it in general, have wanted this :)

**Comment by kutsan** [comment]
> There might have been a reason for it but honestly not sure

The thing that you did wrong is calling a function with `silent!`, since it's a function, everything inside that function will be ignored, even syntax errors like this.

```vim
silent! colorscheme iceberg
```

I've been using `silent!` in my dotfiles like this. I'm 100% sure there is no syntax error and only error can be that colorscheme is not found.

**Comment by ryanoasis** [comment]
Thanks @kutsan good explanation. It's going to take me sometime to merge these in but they'll get in :smile:

**Comment by kutsan** [comment]
I'm really okay with it but just out of curiosity why do you need time to merge these if you think they'll get in?

**Comment by ryanoasis** [comment]
If it was really trivial (docs or simple fix) I would just merge the PR via Github UI but anything else I don't feel comfortable merging without doing so via command line and doing at least a quick sanity check and then pushing up.

Releases will no longer block. Right now the block is just time, some non related project things, then Nerd Fonts 2.0 release issues. Once Nerd Fonts is done I will focus back here.

Thanks for the question, I hope you understand.

I am open to any suggests. I am not afraid to be challenged or if you have any ideas for a better process :smile:

**Comment by kutsan** [comment]
Ah, totally fair enough, I understand!

> I am open to any suggests. I am not afraid to be challenged or if you have any ideas for a better process 😄

That's all I have for now but by the time of progress -since I'm actively using this project- if I got anything, I'll let you know 😁.

**Pull request merged**
