### PR TITLE
changed .go file icon

### PR DESCRIPTION
**Pull request by lujiacn**
#### Requirements (please check off with 'x')

- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

#### What does this Pull Request (PR) do?
Updated go file icon
#### How should this be manually tested?
NA
#### Any background context you can provide?
Looked better
#### What are the relevant tickets (if any)?
NA
#### Screenshots (if appropriate or helpful)
No

### CODE REVIEW

**Comment by ryanoasis** [comment]
Thanks. Unable to see the exact glyph at the moment but will review

**Comment by ryanoasis** [comment]
I am actually torn on this. The current go icon is less 'official' but I find it much easier to identify (especially at smaller font sizes) however the one you updated it to seems to be the official unofficial version..

Would appreciate any other thoughts..

**Comment by lujiacn** [comment]
Thanks for response :) I think it is more personal feeling and feel free to close this request :)
If in some where we can do configuration, replace the icon for specific data type will be great :p

**Comment by ryanoasis** [comment]
@lujiacn Thanks for the understanding! I really hate turning away any PR and actually I think the go icon has change a few times.

Yes there is configuration so you can basically change any of the defaults to be whatever your heart desires :smile: 
```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['go'] = 'ﳑ'
```

**Comment by lujiacn** [comment]
Thank you @ryanoasis, I will close this request.

**Pull request closed without merging**
