### PR TITLE
WIP/RFC: Proper airline extension

### PR DESCRIPTION
**Pull request by blueyed**
#### Requirements (please check off with 'x')
- [x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
#### What does this Pull Request (PR) do?

It improves the integration with vim-airline.

### CODE REVIEW

**Comment by ryanoasis** [comment]
At a glance looks good and makes sense.

This is basically to catch-up with the current and proper way to extend airline?

**Comment by ryanoasis** [comment]
I know it's been a while but is this still WIP?

I have been out of the loop on airline changes is this now the proper way to do it?

**Comment by blueyed** [comment]
I am not using airline myself anymore, but rather my own statusline plugin.
So feel free to close it in case you do not want to adopt it.

**Comment by ryanoasis** [comment]
Thanks for the reply :smile: 

> I am not using airline myself anymore

Any particular reason why your own statusline? More flexibility? More lightweight?

> So feel free to close it in case you do not want to adopt it.

No actually I do want to adopt the proper way to integrate with vim-airline. Maybe what is there now is a bit old and a bit hacky?

**Comment by blueyed** [comment]
> More lightweight?

Yes, it started from there: I noticed when profiling Vim that airline was crazy is some regards.. tried to address it (and some patches came from there), but then I decided to stop.

> Maybe what is there now is a bit old and a bit hacky?

Likely, but my PR might also be not state of the art / up-to-date anymore.

**Comment by ryanoasis** [comment]
Ah I see and can understand that.

> Likely, but my PR might also be not state of the art / up-to-date anymore.

I see, fair enough. I will think about whether to close it or not then. I can see that keeping it open though does remind me that maybe I should take another look to how we are doing the integration :blush:

**Comment by kazukazuinaina** [comment]
@ryanoasis 
I think this patch will also help introduce unit tests for airline.
Since there is a conflict, I think it will be possible to introduce unit tests by creating a new PR and refactoring in stages. What do you think?

**Comment by ryanoasis** [comment]
Yeah I agree if there is a new PR to update integration with current airline we could close this PR.

Init tests for the airline integration ?

**Comment by ryanoasis** [comment]
Closing now that #337 is merged. Thank you both for the contributions :smile:

**Pull request closed without merging**
